spring:
  application:
    name: expression-evaluator
  datasource:
    url: jdbc:h2:mem:expression-evaluator
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
